version: "3.8"

services:

  mongo:
    container_name: mongo
    image: mongo
    expose:
      - "27017"
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/log:/var/log/mongodb/
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    command: mongod --auth

  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - "${BACKEND_PORT}:3000"
    links:
      - mongo
    depends_on:
      - mongo
    restart: always
    environment:
      - NODE_ENV=production
      - MONGO_USERNAME=${MONGO_USERNAME}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DATABASE=${MONGO_DATABASE}
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh mongo:27017 -t 10
        pm2-docker /dist/www.js

  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    links:
      - backend
    depends_on:
      - backend
    restart: always
    command:
      - bash
      - -c
      - |
        /wait-for-it.sh backend:${BACKEND_PORT} -t 10
        nginx -g daemon off;
