version: '3'
services:
  mongo:
    image: mongo
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/log:/var/log/mongodb/
    ports:
      - ${MONGO_PORT}:27017
