import { Block, BlockType, IdType, Page } from '@/schemes';

export const fetchDummyData = (
  pageId: IdType,
): Promise<{ page: Page; blockMap: { [key: string]: Block } }> =>
  new Promise((resolve) => {
    const page = {
      id: '1',
      title: 'Page 01',
      blockIdList: ['1', '2', '3'],
    };

    const blockMap: { [key: string]: Block } = {
      1: {
        id: '1',
        type: BlockType.TEXT,
        value: 'Hello, Bootion!!',
        pageId: '1',
        parentBlockId: null,
        childrenIdList: [],
      },
      2: {
        id: '2',
        type: BlockType.TEXT,
        value: 'Parent Block',
        pageId: '1',
        parentBlockId: null,
        childrenIdList: ['21', '22'],
      },
      21: {
        id: '21',
        type: BlockType.TEXT,
        value: 'Child Block 01',
        pageId: '1',
        parentBlockId: '2',
        childrenIdList: ['211', '212'],
      },
      211: {
        id: '211',
        type: BlockType.TEXT,
        value: 'Grandson Block 01',
        pageId: '1',
        parentBlockId: '21',
        childrenIdList: [],
      },
      212: {
        id: '212',
        type: BlockType.TEXT,
        value: 'Grandson Block 02',
        pageId: '1',
        parentBlockId: '21',
        childrenIdList: [],
      },
      22: {
        id: '22',
        type: BlockType.TEXT,
        value: 'Child Block 02',
        pageId: '1',
        parentBlockId: '2',
        childrenIdList: [],
      },
      3: {
        id: '3',
        type: BlockType.GRID,
        value: 'Grid Block',
        pageId: '1',
        parentBlockId: null,
        childrenIdList: ['31', '32', '33', '34'],
      },
      31: {
        id: '31',
        type: BlockType.COLUMN,
        value: 'Column Block 01',
        pageId: '1',
        parentBlockId: '3',
        childrenIdList: ['311', '312'],
      },
      311: {
        id: '311',
        type: BlockType.TEXT,
        value: 'Row 01 - Col 01',
        pageId: '1',
        parentBlockId: '31',
        childrenIdList: [],
      },
      312: {
        id: '312',
        type: BlockType.TEXT,
        value: 'Row 02 - Col 01',
        pageId: '1',
        parentBlockId: '31',
        childrenIdList: [],
      },
      32: {
        id: '32',
        type: BlockType.COLUMN,
        value: 'Column Block 02',
        pageId: '1',
        parentBlockId: '3',
        childrenIdList: ['321', '322', '323'],
      },
      321: {
        id: '321',
        type: BlockType.TEXT,
        value: 'Row 01 - Col 02',
        pageId: '1',
        parentBlockId: '32',
        childrenIdList: [],
      },
      322: {
        id: '322',
        type: BlockType.TEXT,
        value: 'Row 02 - Col 02',
        pageId: '1',
        parentBlockId: '32',
        childrenIdList: [],
      },
      323: {
        id: '323',
        type: BlockType.TEXT,
        value: 'Row 03 - Col 02',
        pageId: '1',
        parentBlockId: '32',
        childrenIdList: [],
      },
      33: {
        id: '33',
        type: BlockType.COLUMN,
        value: 'Column Block 03',
        pageId: '1',
        parentBlockId: '3',
        childrenIdList: ['331'],
      },
      331: {
        id: '331',
        type: BlockType.TEXT,
        value: 'Row 01 - Col 03',
        pageId: '1',
        parentBlockId: '33',
        childrenIdList: [],
      },
      34: {
        id: '34',
        type: BlockType.COLUMN,
        value: 'Column Block 04',
        pageId: '1',
        parentBlockId: '3',
        childrenIdList: ['341'],
      },
      341: {
        id: '341',
        type: BlockType.TEXT,
        value: 'Row 01 - Col 04',
        pageId: '1',
        parentBlockId: '34',
        childrenIdList: [],
      },
    };
    const data = { page, blockMap };
    setTimeout(() => resolve(data), 500);
  });
