name: Deployment Workflow
on:
  push:
    branches: [ master ]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: deploy production server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.BOOTION_HOST }}
        port: ${{ secrets.BOOTION_PORT }}
        username: ${{ secrets.BOOTUON_USERNAME }}
        key: ${{ secrets.BOOTION_SECRET }}
        script: |
          cd Project18-C-Bootion
          git pull origin master
          docker-compose down --remove-orphans
          docker-compose up -d
